[workspace]
members = [
    "machine-firmware-k210",
    "machine-firmware-qemu",
    "machine-rustsbi",
    "supervisor-kernel",
    "riscv-rt",
]

[patch.crates-io]
riscv-rt = { path = "riscv-rt" }
