[workspace]
members = [
    "machine-firmware-k210",
    "machine-firmware-qemu",
    "machine-rustsbi",
    "supervisor-kernel",
]

[patch.crates-io]
riscv-rt = { git = "https://github.com/rust-embedded/riscv-rt" }
