target := "riscv64imac-unknown-none-elf"
mode := "debug"
build-path := "../target/" + target + "/" + mode + "/"
m-firmware-file := build-path + "machine-firmware-k210"
m-bin-file := build-path + "machine-firmware-k210.bin"

objcopy := "rust-objcopy --binary-architecture=riscv64"
size := "rust-size"

build: firmware
    @{{objcopy}} {{m-firmware-file}} --strip-all -O binary {{m-bin-file}}

firmware:
    @cargo build --target={{target}}

run: build
    @./kflash.py --port /dev/cu.usbserial-6552E58AA60 --terminal {{m-bin-file}}

size: build
    @{{size}} -A -x {{m-firmware-file}} 
