target := "riscv64imac-unknown-none-elf"
mode := "debug"
build-path := "../target/" + target + "/" + mode + "/"
m-firmware-file := build-path + "machine-firmware-k210"

build: firmware

firmware:
    @cargo build --target={{target}}
