MEMORY {
    /* 存储单元的物理地址 */
    SRAM : ORIGIN = 0x80000000, LENGTH = 2M
}

PROVIDE(_stext = 0x80000000);
PROVIDE(_heap_size = 128K);
PROVIDE(_hart_stack_size = 64K);
PROVIDE(_max_hart_id = 7); /* todo */

REGION_ALIAS("REGION_TEXT", SRAM);
REGION_ALIAS("REGION_RODATA", SRAM);
REGION_ALIAS("REGION_DATA", SRAM);
REGION_ALIAS("REGION_BSS", SRAM);
REGION_ALIAS("REGION_HEAP", SRAM);
REGION_ALIAS("REGION_STACK", SRAM);
