target := "riscv64imac-unknown-none-elf"
mode := "debug"
build-path := "../target/" + target + "/" + mode + "/"
s-kernel-file := build-path + "supervisor-app"
s-bin-file := build-path + "supervisor-kernel.bin"

objcopy := "rust-objcopy --binary-architecture=riscv64"

build: kernel
    @{{objcopy}} {{s-kernel-file}} --strip-all -O binary {{s-bin-file}}

kernel:
    @cargo build --target={{target}}
